Repository expo/expo-cli, pull requests merged in 2018-10, with the labels that each got.

#78 [ios] Generate Podfile with ENABLE_PACKAGER_CONNECTION=0 + target iOS 10+
  packages/xdl/src/detach/IosPodsTools.js
Labels: in progress

#56 [xdl] update release channel when publishing an ExpoKit project
  packages/xdl/src/Project.js
Labels: in progress

#87 [circleci] use 'yarn bootstrap' instead of 'bin/boostrap'
  .circleci/config.yml
Labels: in progress

#93 [xdl] '/modules' -> '/packages' in detached workspaces
  packages/xdl/src/detach/IosWorkspace.js
Labels: in progress

#58 [Unimodule] Localization
  packages/xdl/src/modules/config.js
Labels: in progress

#95 [podfile] Add RCT_ENABLE_INSPECTOR=0 to the generated Podfile
  packages/xdl/src/detach/IosPodsTools.js
Labels: in progress

#71 Strip unneeded SDKs code from Android shell app
  packages/xdl/package.json
  packages/xdl/src/detach/AndroidShellApp.js
Labels: enhancement

#98 [xdl] remove generating dynamic macros for every build
  packages/xdl/src/detach/AndroidShellApp.js
Labels: in progress

#100 [xdl] iOS shell app builds propagate xcodebuild errors
  packages/xdl/src/detach/IosShellApp.js
Labels: in progress

#113 [expo-cli] print a reminder about expo publish
  packages/expo-cli/src/commands/build/AndroidBuilder.js
  packages/expo-cli/src/commands/build/BaseBuilder.js
  packages/expo-cli/src/commands/build/IOSBuilder.js
  packages/xdl/src/Project.js
Labels: enhancement, in progress

#114 [exp][xdl] Check if expo SDK version is deprecated before build
  .gitignore
  packages/xdl/src/Versions.js
Labels: in progress

#123 [exp] Don't mutate credentials object
  packages/expo-cli/src/commands/build/IOSBuilder.js
Labels: in progress

#127 [exp] Apple credentials available to supply via cmd
  packages/expo-cli/src/commands/build.js
  packages/expo-cli/src/commands/build/IOSBuilder.js
  packages/xdl/src/Project.js
Labels: in progress

#59 [xdl] fix iOS deployment target for detached apps
  packages/xdl/src/detach/IosAssetArchive.js
  packages/xdl/src/detach/IosPodsTools.js
Labels: in progress
