Repository expo/expo-cli, pull requests merged in 2020-04, with the labels that each got.

#1768 Remove support for managed workflow extensions (.expo) on web
  packages/next-adapter/src/withExpo.ts
  packages/webpack-config/getWebExtensions.js
  packages/webpack-config/src/env/extensions.ts
Labels: Platform: web

#1787 Fix xdl versions
  packages/config/src/__tests__/ConfigParsing-test.js
  packages/config/src/__tests__/fixtures/behavior/custom-location-json/app.json
  packages/config/src/__tests__/fixtures/behavior/custom-location-json/src/app.staging.json
  packages/dev-tools/package.json
  packages/expo-cli/package.json
Labels: bug

#1788 Added `expo-yarn-workspaces`
  package.json
  yarn.lock
Labels: CI, enhancement

#1812 [next-adapter] Fix adding the build script
  packages/next-adapter/src/customize/index.ts
  packages/next-adapter/src/customize/manifest.ts
Labels: Platform: web

#1856 Default to using folder name for projects
  packages/config/src/Config.ts
Labels: Expo config

#1857 Use a default version for configs
  packages/config/src/Config.ts
Labels: Expo config

#1855 [config] Added strict config resolution and file path references
  packages/config/src/Config.ts
  packages/config/src/Config.types.ts
  packages/config/src/__tests__/Config-test.js
  packages/config/src/__tests__/ConfigParsing-test.js
  packages/config/src/__tests__/getConfig-test.js
  packages/config/src/getConfig.ts
  packages/expo-cli/src/commands/__tests__/upgrade-test.ts
Labels: Expo config

#1860 Created method to attempt a modification on an Expo config.
  packages/config/src/Config.ts
  packages/config/src/Config.types.ts
  packages/config/src/__tests__/fixtures/behavior/dynamic-and-static/app.config.js
  packages/config/src/__tests__/fixtures/behavior/dynamic-and-static/app.config.json
  packages/config/src/__tests__/fixtures/behavior/dynamic-and-static/package.json
  packages/config/src/__tests__/fixtures/behavior/dynamic-export-types/exports-function.app.config.js
  packages/config/src/__tests__/fixtures/behavior/dynamic-export-types/exports-object.app.config.js
  packages/config/src/__tests__/fixtures/behavior/no-config/package.json
  packages/config/src/__tests__/fixtures/behavior/static-override/app.config.json
  packages/config/src/__tests__/fixtures/behavior/static-override/package.json
  packages/config/src/__tests__/getConfig-test.js
  packages/config/src/getConfig.ts
  packages/config/src/scripts/read-config.ts
Labels: Expo config

#1862 Created a method for describing the project configs
  packages/config/src/Config.ts
  packages/config/src/__tests__/Config-test.js
  packages/expo-cli/src/commands/start.ts
  packages/expo-cli/src/exp.ts
Labels: Expo config

#1921 Create init commit for projects
  packages/expo-cli/src/commands/init.ts
  packages/xdl/src/Exp.ts
Labels: enhancement

#1940 Fallback on insecure HTTPS
  packages/webpack-config/src/addons/withDevServer.ts
Labels: Platform: web

#1942 [webpack-config] fix: update workbox
  packages/webpack-config/package.json
  packages/webpack-config/src/addons/withWorkbox.ts
  yarn.lock
Labels: Platform: web

#1947 [webpack-config] Resolve babel preset expo from a global CLI
  packages/webpack-config/src/loaders/createBabelLoader.ts
Labels: Platform: web

#1987 Deprecate ios and android commands
  CHANGELOG.md
  packages/expo-cli/src/commands/android.ts
  packages/expo-cli/src/commands/ios.ts
Labels: enhancement

#1989 [expo-cli] Improve readability of asyncActionProjectDir
  packages/expo-cli/src/commands/android.ts
  packages/expo-cli/src/commands/apply.ts
  packages/expo-cli/src/commands/build-native/index.ts
  packages/expo-cli/src/commands/build/index.ts
  packages/expo-cli/src/commands/bundle-assets.ts
  packages/expo-cli/src/commands/client/index.ts
  packages/expo-cli/src/commands/doctor.ts
  packages/expo-cli/src/commands/eject.ts
  packages/expo-cli/src/commands/export.ts
  packages/expo-cli/src/commands/fetch/index.ts
  packages/expo-cli/src/commands/ios.ts
  packages/expo-cli/src/commands/opt-into-google-play-signing.ts
  packages/expo-cli/src/commands/prepare-detached-build.ts
  packages/expo-cli/src/commands/publish-info.ts
  packages/expo-cli/src/commands/publish-modify.ts
  packages/expo-cli/src/commands/publish.ts
  packages/expo-cli/src/commands/push-creds.ts
  packages/expo-cli/src/commands/start.ts
  packages/expo-cli/src/commands/upload.ts
  packages/expo-cli/src/commands/url.ts
  packages/expo-cli/src/commands/webhooks.ts
  packages/expo-cli/src/exp.ts
Labels: enhancement

#2023 Revert workbox upgrade
  packages/webpack-config/package.json
  packages/webpack-config/src/addons/withWorkbox.ts
  yarn.lock
Labels: Platform: web

#2026 Added docs for uri-scheme
  packages/uri-scheme/README.md
Labels: enhancement

#2018 Added web info to diagnostics
  packages/expo-cli/src/commands/diagnostics.ts
Labels: Platform: web, enhancement

#2029 [expo-cli] client:ios -- default to using Apple ID email address
  packages/expo-cli/src/commands/client/index.ts
Labels: enhancement

#2033 [config] Remove jest message utils
  package.json
  packages/config/package.json
  packages/config/src/getConfig.ts
  yarn.lock
Labels: 🧹 chore

#2039 [next-adapter] Create typings for Document
  packages/next-adapter/document.d.ts
  packages/next-adapter/package.json
Labels: Platform: web, enhancement

#2038 [electron-adapter] Updated example to SDK 37
  packages/electron-adapter/example/app.json
  packages/electron-adapter/example/assets/icon.png
  packages/electron-adapter/example/assets/splash.png
  packages/electron-adapter/example/babel.config.js
  packages/electron-adapter/example/package.json
  packages/electron-adapter/example/yarn.lock
Labels: 🧹 chore

#2037 Migrate all packages to use globby
  packages/config/package.json
  packages/config/src/android/Package.ts
  packages/config/src/ios/BundleIdentifier.ts
  packages/config/src/ios/Entitlements.ts
  packages/config/src/ios/utils/Xcodeproj.ts
  packages/expo-cli/package.json
  packages/expo-cli/src/commands/apply/configureAndroidProjectAsync.ts
  packages/expo-codemod/package.json
  packages/expo-optimize/package.json
  packages/expo-optimize/src/assets.ts
  packages/metro-config/package.json
  packages/pwa/package.json
  packages/uri-scheme/package.json
  packages/uri-scheme/src/Android.ts
  packages/uri-scheme/src/Ios.ts
  packages/xdl/package.json
  packages/xdl/src/detach/IosSetBundleIdentifier.ts
  yarn.lock
Labels: 🧹 chore

#2040 Only use puppeteer in CI
  packages/webpack-config/package.json
  yarn.lock
Labels: Platform: web

#2035 Delete unused package manager from expo-cli
  packages/config/package.json
  packages/config/src/Project.ts
  packages/config/src/paths/paths.ts
  packages/expo-cli/package.json
  packages/expo-cli/src/PackageManager.ts
  packages/expo-cli/src/commands/eject/LegacyEject.ts
  packages/package-manager/package.json
  packages/webpack-config/package.json
  packages/webpack-config/src/env/paths.ts
  packages/xdl/package.json
  packages/xdl/src/Webpack.ts
  yarn.lock
Labels: 🧹 chore
