Repository expo/expo-cli, pull requests merged in 2020-05, with the labels that each got.

#1726 chore: update webpack
  package.json
  packages/webpack-config/package.json
  packages/webpack-config/src/plugins/ExpoDefinePlugin.ts
  packages/webpack-config/src/utils/search.ts
  packages/xdl/package.json
  packages/xdl/src/Web.ts
  yarn.lock
Labels: Platform: web

#2086 Add a default project root for easier use with Webpack CLI
  packages/webpack-config/src/index.ts
Labels: Platform: web

#2137 [webpack-config] with platform source maps
  packages/webpack-config/src/addons/index.ts
  packages/webpack-config/src/addons/withSourceMaps.ts
  packages/webpack-config/src/webpack.config.ts
Labels: enhancement

#2151 [optimize] Extern the config package
  packages/expo-optimize/package.json
Labels: bug

#2158 Added warnings when nothing happens in URI scheme
  packages/uri-scheme/src/URIScheme.ts
Labels: enhancement

#2175 [webpack-config] test externals
  packages/webpack-config/src/addons/__tests__/withUnimodules-test.js
  packages/webpack-config/src/addons/withUnimodules.ts
Labels: Platform: web

#2173 update e2e tests to 37
  packages/electron-adapter/example/package.json
  packages/electron-adapter/example/yarn.lock
  packages/webpack-config/e2e/.gitignore
  packages/webpack-config/e2e/__tests__/basic-test.js
  packages/webpack-config/e2e/basic/app.config.js
  packages/webpack-config/e2e/basic/app.json
  packages/webpack-config/e2e/basic/package.json
  packages/webpack-config/e2e/basic/yarn.lock
  packages/webpack-config/e2e/custom-homepage/.gitignore
  packages/webpack-config/e2e/custom-homepage/app.json
  packages/webpack-config/e2e/custom-homepage/icon.png
  packages/webpack-config/e2e/custom-homepage/package.json
  packages/webpack-config/e2e/custom-homepage/yarn.lock
  packages/webpack-config/e2e/minimum/.gitignore
  packages/webpack-config/e2e/minimum/package.json
  packages/webpack-config/e2e/minimum/yarn.lock
  packages/webpack-config/package.json
  yarn.lock
Labels: Platform: web

#2184 [xdl] Deprecate Web module in favor of Webpack module
  packages/expo-cli/src/commands/start.ts
  packages/xdl/src/Web.ts
  packages/xdl/src/Webpack.ts
  packages/xdl/src/webpack-utils/WebpackEnvironment.ts
  packages/xdl/src/webpack-utils/createWebpackCompiler.ts
Labels: 🧹 chore

#2185 chore: update dependencies
  packages/config/package.json
  packages/dev-server/package.json
  packages/expo-cli/package.json
  packages/expo-codemod/package.json
  packages/expo-optimize/package.json
  packages/json-file/package.json
  packages/package-manager/package.json
  packages/pwa/package.json
  packages/uri-scheme/package.json
  packages/xdl/package.json
  yarn.lock
Labels: 🧹 chore

#2186 [webpack-config] Invert npmignore, use files instead
  packages/webpack-config/.npmignore
  packages/webpack-config/package.json
Labels: 🧹 chore

#2177 Prevent overwriting environment variables in Next.js
  packages/next-adapter/src/withExpo.ts
  packages/webpack-config/README.md
  packages/webpack-config/src/addons/withUnimodules.ts
  packages/webpack-config/src/plugins/ExpoDefinePlugin.ts
  packages/webpack-config/src/plugins/__tests__/ExpoDefinePlugin-test.ts
Labels: Platform: web

#2171 Remove fs extra from package-manager
  packages/expo-cli/src/commands/publish-modify.ts
  packages/expo-cli/src/commands/url.ts
  packages/json-file/src/JsonFile.ts
  packages/package-manager/package.json
  packages/package-manager/src/CocoaPodsPackageManager.ts
  packages/package-manager/src/NodePackageManagers.ts
  packages/package-manager/src/PackageManager.ts
  packages/package-manager/src/__tests__/CocoaPodsPackageManager-test.ts
  packages/package-manager/src/utils/isYarnOfflineAsync.ts
Labels: enhancement, 🧹 chore
