Repository expo/expo-cli, pull requests merged in 2020-09, with the labels that each got.

#2542 Migrate SetupIosPush to prompts
  packages/expo-cli/src/credentials/views/SetupIosPush.ts
Labels: 🧹 chore

#2541 [cli] simulator upgrades
  CHANGELOG.md
  packages/dev-tools/server/graphql/GraphQLSchema.ts
  packages/expo-cli/src/commands/client/index.ts
  packages/expo-cli/src/commands/start/TerminalUI.ts
  packages/expo-cli/src/commands/upgrade.ts
  packages/expo-cli/src/urlOpts.ts
  packages/xdl/src/SimControl.ts
  packages/xdl/src/Simulator.ts
  packages/xdl/src/Xcode.ts
  packages/xdl/src/__integration_tests__/Simulator-test.ts
Labels: enhancement

#2550 [xdl] Improved Android module
  CHANGELOG.md
  packages/dev-tools/server/graphql/GraphQLSchema.ts
  packages/expo-cli/src/commands/start/TerminalUI.ts
  packages/expo-cli/src/urlOpts.ts
  packages/xdl/src/Android.ts
Labels: adb, android, android-emulator, android-physical, enhancement

#2558 Fix copy webpack plugin for web overrides
  CHANGELOG.md
  packages/webpack-config/src/webpack.config.ts
Labels: Platform: web

#2562 Created prompts module for unifying terminal UI interactions
  packages/expo-cli/src/commands/start/TerminalUI.ts
  packages/xdl/src/Android.ts
  packages/xdl/src/Prompts.ts
  packages/xdl/src/Simulator.ts
  packages/xdl/src/xdl.ts
Labels: 🧹 chore

#2567 [apply] Added ability to remove entitlements
  packages/config/src/ios/Entitlements.ts
Labels: expo apply

#2563 Only prompt to upgrade once in a single run per device
  packages/xdl/src/Android.ts
  packages/xdl/src/Simulator.ts
Labels: enhancement

#2517 [chore] Split asset code out of Projects file
  packages/expo-cli/src/commands/publish.ts
  packages/xdl/src/Project.ts
  packages/xdl/src/ProjectAssets.ts
  packages/xdl/src/detach/IosPodsTools.js
Labels: 🧹 chore

#2087 [config] automate android icon
  CHANGELOG.md
  packages/config/src/android/AdaptiveIcon.ts
  packages/config/src/android/Colors.ts
  packages/config/src/android/Icon.ts
  packages/config/src/android/__tests__/Icon-test.ts
  packages/config/src/android/__tests__/fixtures/adaptiveIconBackground.png
  packages/config/src/android/__tests__/fixtures/adaptiveIconForeground.png
  packages/config/src/android/__tests__/fixtures/icon.ts
  packages/config/src/android/index.ts
  packages/expo-cli/src/commands/apply/configureAndroidProjectAsync.ts
  packages/image-utils/src/Image.ts
  packages/image-utils/src/Image.types.ts
  packages/image-utils/src/index.ts
  packages/image-utils/src/jimp.ts
  yarn.lock
Labels: enhancement, expo apply

#2571 Use prompts package for simulator/emulator
  packages/xdl/package.json
  packages/xdl/src/Android.ts
  packages/xdl/src/Prompts.ts
  packages/xdl/src/Simulator.ts
Labels: enhancement

#2578 [cli] Added workflow info
  packages/expo-cli/src/commands/diagnostics.ts
Labels: enhancement

#2575 Migrate upgrade command to prompts
  packages/expo-cli/src/commands/upgrade.ts
  packages/expo-cli/src/prompts.ts
Labels: 🧹 chore

#2588 [xdl] Delete deprecated web module
  CHANGELOG.md
  packages/xdl/src/Web.ts
  packages/xdl/src/xdl.ts
Labels: 🧹 chore

#2592 Globally type xcode module
  packages/config/src/ios/BundleIdentifier.ts
  packages/config/src/ios/Entitlements.ts
  packages/config/src/ios/utils/Xcodeproj.ts
  packages/configure-splash-screen/src/ios/pbxproj.ts
  packages/configure-splash-screen/src/xcode/index.ts
  packages/xdl/src/detach/IosSetBundleIdentifier.ts
  ts-declarations/xcode/index.d.ts
Labels: 🧹 chore

#2576 [export] Prompt for public-url and list conflicts
  CHANGELOG.md
  packages/expo-cli/src/commands/__tests__/export-test.ts
  packages/expo-cli/src/commands/export.ts
  packages/expo-cli/src/commands/utils/Tar.ts
Labels: enhancement, expo export

#2597 [eject] Skip warnings notice when no warnings are thrown
  packages/expo-cli/src/commands/eject/Eject.ts
Labels: 🧹 chore

#2590 [xdl] delete deprecated Exp code
  CHANGELOG.md
  packages/expo-cli/package.json
  packages/expo-cli/src/commands/init.ts
  packages/expo-cli/src/commands/push-creds-web.ts
  packages/expo-cli/src/commands/upgrade.ts
  packages/xdl/package.json
  packages/xdl/src/Exp.ts
Labels: 🧹 chore

#2566 [apply] Added support to Facebook
  CHANGELOG.md
  packages/config/src/android/Facebook.ts
  packages/config/src/android/Strings.ts
  packages/config/src/android/__tests__/Facebook-test.js
  packages/config/src/ios/Facebook.ts
  packages/config/src/ios/__tests__/Facebook-test.ts
Labels: expo apply

#2594 Add support for escaped names in eject and bare init
  packages/expo-cli/e2e/__tests__/eject-test.ts
  packages/expo-cli/e2e/__tests__/init-test.ts
  packages/xdl/src/Exp.ts
Labels: enhancement

#2577 [xdl] split manifest handler out of Project
  packages/xdl/src/Project.ts
  packages/xdl/src/ProjectAssets.ts
  packages/xdl/src/__tests__/Project-test.ts
  packages/xdl/src/project/ExpSchema.ts
  packages/xdl/src/project/ManifestHandler.ts
  packages/xdl/src/project/__tests__/ExpSchema-test.ts
  packages/xdl/src/project/__tests__/ManifestHandler-test.ts
  packages/xdl/src/project/__tests__/__snapshots__/ManifestHandler-test.ts.snap
  packages/xdl/src/project/__tests__/fixtures/icon.png
Labels: expo start, 🧹 chore

#2595 Added extra time to failing tests
  packages/expo-cli/src/commands/eas-build/build/builders/__tests__/iOSBuilder-test.ts
  packages/expo-cli/src/credentials/provider/__tests__/AndroidCredentialsProvider-test.ts
  packages/expo-cli/src/credentials/provider/__tests__/iOSCredentialsProvider-test.ts
Labels: 🧹 chore

#2606 [eject] update config validation messages
  packages/expo-cli/src/commands/eject/ConfigValidation.ts
Labels: 🧹 chore

#2604 [cli] improve init
  packages/expo-cli/e2e/__tests__/init-test.ts
  packages/expo-cli/src/commands/__tests__/export-test.ts
  packages/expo-cli/src/commands/eject/Eject.ts
  packages/expo-cli/src/commands/export.ts
  packages/expo-cli/src/commands/init.ts
  packages/expo-cli/src/commands/utils/CreateApp.ts
  packages/expo-cli/src/commands/utils/__tests__/CreateApp-test.ts
Labels: enhancement

#2602 fix(cli): let publish command respect clear flag to clear cache
  packages/expo-cli/src/commands/publish.ts
Labels: bug

#2614 [cli] Clean up TerminalUI
  packages/expo-cli/src/commands/start/TerminalUI.ts
  packages/expo-cli/src/exit.ts
Labels: 🧹 chore

#2616 warn the user when the bundle ID or package name is already in use
  packages/expo-cli/src/commands/eject/ConfigValidation.ts
  packages/expo-cli/src/commands/utils/url.ts
Labels: enhancement

#2621 [eject] Added no-install and npm args to eject
  packages/expo-cli/src/commands/eject.ts
  packages/expo-cli/src/commands/eject/Eject.ts
  packages/expo-cli/src/commands/init.ts
  packages/expo-cli/src/commands/utils/CreateApp.ts
  packages/expo-cli/src/log.ts
Labels: enhancement

#2620 [eject] Make gitignore and native project step idempotent
  packages/config/src/android/Package.ts
  packages/expo-cli/src/commands/eject/Eject.ts
  packages/expo-cli/src/commands/eject/__tests__/Eject-test.ts
  packages/expo-cli/src/commands/utils/GitIgnore.ts
  packages/expo-cli/src/commands/utils/__tests__/GitIgnore-test.ts
  packages/expo-cli/src/commands/utils/logConfigWarnings.ts
Labels: enhancement

#2626 Added better logs for invalid custom config paths
  packages/expo-cli/src/commands/init.ts
  packages/expo-cli/src/exp.ts
Labels: enhancement

#2627 Extract introspect out of expo-cli
  packages/expo-cli/package.json
  packages/expo-cli/scripts/introspect.ts
  packages/expo-cli/src/exp.ts
Labels: 🧹 chore

#2628 Delete Circle CI
  .circleci/config.yml
  .github/workflows/test.yml
Labels: 🧹 chore

#2636 [expo start] remove extra config reads
  packages/dev-tools/server/dev-server.ts
  packages/expo-cli/src/commands/start.ts
  packages/expo-cli/src/commands/upgrade.ts
  packages/expo-cli/src/commands/utils/PublishUtils.ts
  packages/xdl/src/Project.ts
Labels: 🧹 chore

#2642 [config] Unify metadata manifest helpers
  packages/config/src/android/Facebook.ts
Labels: 🧹 chore

#2635 Improve JSON error formatting
  packages/expo-cli/src/commands/eject/Eject.ts
  packages/expo-cli/src/commands/upgrade.ts
  packages/expo-cli/src/exp.ts
  packages/json-file/src/JsonFile.ts
  packages/json-file/src/JsonFileError.ts
  packages/xdl/src/Android.ts
  packages/xdl/src/Project.ts
  packages/xdl/src/detach/IosPodsTools.js
  packages/xdl/src/project/Doctor.ts
  packages/xdl/src/project/ManifestHandler.ts
Labels: enhancement

#2625 Remove external config evaluation script
  packages/config/package.json
  packages/config/src/__tests__/getConfig-test.js
  packages/config/src/evalConfig.ts
  packages/config/src/getConfig.ts
  packages/config/src/scripts/read-config.ts
  yarn.lock
Labels: Expo config, enhancement

#2605 [cli] Migrate all confirm prompts to prompts package
  packages/expo-cli/src/__mocks__/prompts.ts
  packages/expo-cli/src/accounts.ts
  packages/expo-cli/src/commands/build/index.ts
  packages/expo-cli/src/commands/build/ios/IOSBuilder.ts
  packages/expo-cli/src/commands/client/index.ts
  packages/expo-cli/src/commands/eas-build/utils/git.ts
  packages/expo-cli/src/commands/eject.ts
  packages/expo-cli/src/commands/upgrade.ts
  packages/expo-cli/src/commands/utils/PublishUtils.ts
  packages/expo-cli/src/commands/utils/maybeBailOnGitStatusAsync.ts
  packages/expo-cli/src/credentials/credentialsJson/__tests__/update-test.ts
  packages/expo-cli/src/credentials/credentialsJson/update.ts
  packages/expo-cli/src/credentials/views/AndroidCredentials.ts
  packages/expo-cli/src/credentials/views/AndroidKeystore.ts
  packages/expo-cli/src/credentials/views/IosDistCert.ts
  packages/expo-cli/src/credentials/views/IosProvisioningProfile.ts
  packages/expo-cli/src/credentials/views/IosPushCredentials.ts
  packages/expo-cli/src/credentials/views/Select.ts
  packages/expo-cli/src/credentials/views/SetupIosBuildCredentials.ts
  packages/expo-cli/src/credentials/views/SetupIosPush.ts
  packages/expo-cli/src/credentials/views/__tests__/AndroidKeystore-Remove-test.ts
  packages/expo-cli/src/prompts.ts
Labels: 🧹 chore

#2622 Generate types for Expo config
  packages/config-types/.gitignore
  packages/config-types/LICENSE
  packages/config-types/README.md
  packages/config-types/package.json
  packages/config-types/scripts/generate.ts
  packages/config-types/src/index.ts
  packages/config-types/tsconfig.json
  packages/config/package.json
  packages/config/src/Config.ts
  packages/config/src/Config.types.ts
  packages/config/src/android/Scheme.ts
  packages/config/src/android/UserInterfaceStyle.ts
  packages/config/src/ios/Scheme.ts
  packages/config/src/ios/UserInterfaceStyle.ts
  packages/expo-cli/src/commands/apply.ts
  packages/expo-cli/src/commands/eas-build/build/metadata.ts
  packages/expo-cli/src/commands/eject/Eject.ts
  packages/expo-cli/src/commands/upgrade.ts
  packages/expo-cli/src/exp.ts
  packages/pwa/src/Manifest.ts
  packages/pwa/src/Manifest.types.ts
  packages/webpack-config/src/addons/withTypeScriptAsync.ts
  packages/webpack-config/src/plugins/ExpoDefinePlugin.ts
  packages/webpack-config/src/types.ts
  packages/webpack-config/src/webpack.config.ts
  packages/xdl/src/Android.ts
  packages/xdl/src/EmbeddedAssets.ts
  packages/xdl/src/Project.ts
  packages/xdl/src/ProjectAssets.ts
  packages/xdl/src/detach/IosPodsTools.js
  packages/xdl/src/project/ManifestHandler.ts
  yarn.lock
Labels: Expo config

#2647 resolve locales from project root
  packages/xdl/src/Project.ts
  packages/xdl/src/UrlUtils.ts
  packages/xdl/src/detach/ExponentTools.ts
  packages/xdl/src/detach/IosLocalization.js
  packages/xdl/src/detach/IosNSBundle.ts
  yarn.lock
Labels: 🧹 chore

#2643 Transpile expo/config in expo-optimize
  packages/babel-preset-cli/index.js
  packages/config/src/evalConfig.ts
  packages/expo-optimize/package.json
Labels: 🧹 chore

#2649 Log about upload after build:ios completes
  packages/expo-cli/src/commands/build/BaseBuilder.ts
Labels: 🧹 chore

#2651 remove case sort from lint
  .eslintrc.js
Labels: 🧹 chore

#2652 Remove unused babel.config.js
  packages/config/babel.config.js
  packages/configure-splash-screen/babel.config.js
  packages/dev-server/babel.config.js
  packages/expo-codemod/babel.config.js
  packages/json-file/babel.config.js
  packages/metro-config/babel.config.js
  packages/package-manager/babel.config.js
  packages/plist/babel.config.js
  packages/pwa/babel.config.js
  packages/schemer/babel.config.js
  packages/uri-scheme/babel.config.js
  packages/webpack-config/babel.config.js
  packages/webpack-config/jest/e2e-test-config.json
Labels: 🧹 chore

#2653 remove extra .gitignores
  .gitignore
  packages/config-types/.gitignore
  packages/config/.gitignore
  packages/configure-splash-screen/.gitignore
  packages/dev-server/.gitignore
  packages/dev-tools/.gitignore
  packages/electron-adapter/.gitignore
  packages/expo-cli/.gitignore
  packages/expo-codemod/.gitignore
  packages/expo-optimize/.gitignore
  packages/image-utils/.gitignore
  packages/json-file/.gitignore
  packages/metro-config/.gitignore
  packages/next-adapter/.gitignore
  packages/osascript/.gitignore
  packages/package-manager/.gitignore
  packages/plist/.gitignore
  packages/pod-install/.gitignore
  packages/pwa/.gitignore
  packages/schemer/.gitignore
  packages/uri-scheme/.gitignore
  packages/webpack-config/.gitignore
  packages/xdl/.gitignore
Labels: 🧹 chore

#2654 [osascript] change lib folder to build
  .gitignore
  packages/osascript/package.json
  packages/osascript/tsconfig.json
Labels: 🧹 chore

#2661 Fix: Next warning Expected Document Component Html was not rendered
  packages/next-adapter/document.js
Labels: Platform: web, 🧹 chore

#2665 [config] cleanup android
  packages/config/src/android/Branch.ts
  packages/config/src/android/Colors.ts
  packages/config/src/android/Facebook.ts
  packages/config/src/android/GoogleMapsApiKey.ts
  packages/config/src/android/GoogleMobileAds.ts
  packages/config/src/android/Icon.ts
  packages/config/src/android/IntentFilters.ts
  packages/config/src/android/Manifest.ts
  packages/config/src/android/NavigationBar.ts
  packages/config/src/android/Orientation.ts
  packages/config/src/android/PrimaryColor.ts
  packages/config/src/android/RootViewBackgroundColor.ts
  packages/config/src/android/StatusBar.ts
  packages/config/src/android/Strings.ts
  packages/config/src/android/Styles.ts
  packages/config/src/android/Updates.ts
  packages/config/src/android/UserInterfaceStyle.ts
  packages/config/src/android/Version.ts
  packages/config/src/android/__tests__/Branch-test.js
  packages/config/src/android/__tests__/Facebook-test.js
  packages/config/src/android/__tests__/GoogleMapsApiKey-test.js
  packages/config/src/android/__tests__/GoogleMobileAds-test.js
  packages/config/src/android/__tests__/IntentFilters-test.js
  packages/config/src/android/__tests__/NavigationBar-test.js
  packages/config/src/android/__tests__/Orientation-test.js
  packages/config/src/android/__tests__/PrimaryColor-test.js
  packages/config/src/android/__tests__/RootViewBackgroundColor-test.js
  packages/config/src/android/__tests__/Scheme-test.js
  packages/config/src/android/__tests__/StatusBar-test.js
  packages/config/src/android/__tests__/Styles-test.ts
  packages/config/src/android/__tests__/Updates-test.js
  packages/config/src/android/__tests__/UserInterfaceStyle-test.js
Labels: 🧹 chore

#2684 [xdl] Remove unused methods from Project module
  CHANGELOG.md
  packages/expo-cli/src/commands/utils/PublishUtils.ts
  packages/xdl/src/Project.ts
Labels: 🧹 chore

#2674 [config] improve modules
  packages/config/src/android/AllowBackup.ts
  packages/config/src/android/Colors.ts
  packages/config/src/android/Facebook.ts
  packages/config/src/android/Icon.ts
  packages/config/src/android/Name.ts
  packages/config/src/android/Package.ts
  packages/config/src/android/UserInterfaceStyle.ts
  packages/config/src/android/Version.ts
  packages/config/src/android/__tests__/Colors-test.ts
  packages/config/src/ios/CustomInfoPlistEntries.ts
  packages/config/src/ios/Entitlements.ts
  packages/config/src/ios/Facebook.ts
  packages/config/src/ios/Google.ts
  packages/config/src/ios/IosConfig.types.ts
  packages/config/src/ios/Name.ts
  packages/config/src/ios/Orientation.ts
  packages/config/src/ios/Resources.ts
  packages/config/src/ios/Scheme.ts
  packages/config/src/ios/Updates.ts
  packages/config/src/ios/UserInterfaceStyle.ts
  packages/config/src/ios/UsesNonExemptEncryption.ts
  packages/config/src/ios/Version.ts
  packages/config/src/ios/__tests__/Updates-test.ts
  packages/xdl/src/detach/IosPlist.ts
Labels: 🧹 chore

#2681 Support unauthorized devices
  packages/xdl/src/Android.ts
  packages/xdl/src/logs/TerminalLink.ts
Labels: enhancement

#2690 @expo/config-types@39.0.1
  packages/config-types/package.json
  packages/config-types/src/index.ts
Labels: 🧹 chore

#2691 [config] Resolve inline locales
  packages/config/src/ios/Locales.ts
  packages/config/src/ios/__tests__/Locales-test.ts
Labels: enhancement

#2624 [config][eject] Added ios.entitlements
  packages/config-types/src/index.ts
  packages/config/src/ios/Entitlements.ts
  packages/expo-cli/src/commands/apply/configureIOSProjectAsync.ts
  packages/xdl/src/detach/IosNSBundle.ts
Labels: enhancement

#2695 [config] Created Paths module
  packages/config/src/android/Colors.ts
  packages/config/src/android/Icon.ts
  packages/config/src/android/Manifest.ts
  packages/config/src/android/NavigationBar.ts
  packages/config/src/android/Paths.ts
  packages/config/src/android/PrimaryColor.ts
  packages/config/src/android/RootViewBackgroundColor.ts
  packages/config/src/android/StatusBar.ts
  packages/config/src/android/Strings.ts
  packages/config/src/android/Styles.ts
  packages/config/src/android/__tests__/Colors-test.ts
  packages/config/src/android/__tests__/NavigationBar-test.js
  packages/config/src/android/__tests__/Paths-test.ts
  packages/config/src/android/__tests__/PrimaryColor-test.js
  packages/config/src/android/__tests__/RootViewBackgroundColor-test.js
  packages/config/src/android/__tests__/StatusBar-test.js
  packages/config/src/android/index.ts
  packages/expo-cli/src/commands/apply/configureAndroidProjectAsync.ts
  packages/expo-cli/src/commands/init.ts
Labels: 🧹 chore

#2707 [config-types] android.intentFilters.data type fix
  packages/config-types/package.json
  packages/config-types/src/index.ts
  packages/config/package.json
  packages/config/src/android/IntentFilters.ts
  packages/expo-cli/src/commands/client/clientBuildApi.ts
  packages/expo-cli/src/commands/eject/Eject.ts
  packages/xdl/src/project/ExpSchema.ts
  packages/xdl/src/project/ManifestHandler.ts
Labels: 🧹 chore

#2715 [config-types] Rename root config file to ExpoConfig
  packages/config-types/package.json
  packages/config-types/scripts/generate.ts
  packages/config-types/src/ExpoConfig.ts
Labels: 🧹 chore

#2716 [config-types] Split up platform configs
  packages/config-types/src/ExpoConfig.ts
  packages/config/src/android/IntentFilters.ts
Labels: 🧹 chore

#2722 [config-types] Remove loading object
  packages/config-types/src/ExpoConfig.ts
Labels: 🧹 chore

#2721 [cli] Fix command help options order
  packages/expo-cli/src/exp.ts
Labels: bug

#2719 use learn more link
  packages/expo-cli/src/commands/upload/submission-service/android/ServiceAccountSource.ts
  packages/expo-cli/src/commands/upload/submission-service/utils/errors.ts
Labels: 🧹 chore
