Repository expo/expo-cli, pull requests merged in 2020-10, with the labels that each got.

#2742 [xdl] Fix simulator picking when multiple device versions exist
  packages/xdl/src/Simulator.ts
Labels: bug

#2749 [configure-splash-screen]<chore>: Update test file names to follow naming convention
  packages/configure-splash-screen/src/__tests__/cli-command-test.ts
  packages/configure-splash-screen/src/android/__tests__/AndroidManifest.xml-test.ts
  packages/configure-splash-screen/src/android/__tests__/Colors.xml-test.ts
  packages/configure-splash-screen/src/android/__tests__/Drawable.xml-test.ts
  packages/configure-splash-screen/src/android/__tests__/Drawables-test.ts
  packages/configure-splash-screen/src/android/__tests__/MainActivity-test.ts
  packages/configure-splash-screen/src/android/__tests__/Styles.xml-test.ts
  packages/configure-splash-screen/src/android/__tests__/index-test.ts
  packages/configure-splash-screen/src/ios/__tests__/BackgroundAsset-test.ts
  packages/configure-splash-screen/src/ios/__tests__/ImageAsset-test.ts
  packages/configure-splash-screen/src/ios/__tests__/Info.plist-test.ts
  packages/configure-splash-screen/src/ios/__tests__/Storyboard-test.ts
  packages/configure-splash-screen/src/ios/__tests__/index-test.ts
  packages/configure-splash-screen/src/validators/__tests__/android-test.ts
  packages/configure-splash-screen/src/validators/__tests__/ios-test.ts
Labels: 🧹 chore

#2784 [config] Created paths module for ios
  packages/config/src/Errors.ts
  packages/config/src/Modules.ts
  packages/config/src/android/Paths.ts
  packages/config/src/android/__tests__/Resources-test.ts
  packages/config/src/ios/BundleIdentifier.ts
  packages/config/src/ios/DeviceFamily.ts
  packages/config/src/ios/Entitlements.ts
  packages/config/src/ios/Google.ts
  packages/config/src/ios/Paths.ts
  packages/config/src/ios/Scheme.ts
  packages/config/src/ios/__tests__/BundleIdentifier-test.ts
  packages/config/src/ios/__tests__/DeviceFamily-test.ts
  packages/config/src/ios/__tests__/Paths-test.ts
  packages/config/src/ios/index.ts
  packages/config/src/ios/utils/Xcodeproj.ts
  packages/expo-cli/src/commands/apply/configureIOSProjectAsync.ts
Labels: 🧹 chore

#2797 [config] fix entitlements functionality
  packages/config/src/ios/Entitlements.ts
  packages/config/src/ios/Paths.ts
  packages/config/src/ios/__tests__/Entitlements-test.ts
  packages/config/src/ios/__tests__/Paths-test.ts
Labels: Expo config, expo eject

#2811 [config] disjointed features from plugins ios
  packages/config/src/android/StatusBar.ts
  packages/config/src/android/__tests__/Icon-test.ts
  packages/config/src/ios/DeviceFamily.ts
  packages/config/src/ios/Entitlements.ts
  packages/config/src/ios/__tests__/DeviceFamily-test.ts
  packages/config/src/ios/__tests__/Icons-test.ts
  packages/config/src/ios/__tests__/Locales-test.ts
  packages/config/src/ios/__tests__/Paths-test.ts
  packages/config/src/ios/__tests__/utils/getDirFromFS.ts
  packages/config/src/ios/utils/Xcodeproj.ts
  packages/config/src/plugins/__tests__/fixtures/react-native-project.ts
  ts-declarations/xcode/index.d.ts
Labels: 🧹 chore

#2834 [xdl] Clean up UrlUtils
  packages/xdl/src/UrlUtils.ts
  packages/xdl/src/__tests__/UrlUtils-test.ts
  packages/xdl/src/project/ManifestHandler.ts
  packages/xdl/src/project/__tests__/ManifestHandler-test.ts
Labels: 🧹 chore
