Repository expo/expo-cli, pull requests merged in 2020-08, with the labels that each got.

#2410 [expo-cli] Show better errors in non-interactive mode
  packages/expo-cli/src/commands/build/AndroidBuilder.ts
  packages/expo-cli/src/commands/build/ios/IOSBuilder.ts
  packages/expo-cli/src/commands/client/index.ts
  packages/expo-cli/src/commands/credentials.ts
  packages/expo-cli/src/commands/eas-build/build/__tests__/credentials-test.ts
  packages/expo-cli/src/commands/eas-build/build/action.ts
  packages/expo-cli/src/commands/eas-build/build/builders/AndroidBuilder.ts
  packages/expo-cli/src/commands/eas-build/build/builders/iOSBuilder.ts
  packages/expo-cli/src/commands/eas-build/build/credentials.ts
  packages/expo-cli/src/commands/eas-build/build/types.ts
  packages/expo-cli/src/commands/fetch/android.ts
  packages/expo-cli/src/credentials/context.ts
  packages/expo-cli/src/credentials/provider/AndroidCredentialsProvider.ts
  packages/expo-cli/src/credentials/provider/iOSCredentialsProvider.ts
  packages/expo-cli/src/credentials/views/AndroidCredentials.ts
  packages/expo-cli/src/credentials/views/AndroidKeystore.ts
  packages/expo-cli/src/credentials/views/AndroidPushCredentials.ts
  packages/expo-cli/src/credentials/views/IosDistCert.ts
  packages/expo-cli/src/credentials/views/IosProvisioningProfile.ts
  packages/expo-cli/src/credentials/views/IosPushCredentials.ts
  packages/expo-cli/src/credentials/views/Select.ts
  packages/expo-cli/src/credentials/views/SetupIosBuildCredentials.ts
  packages/expo-cli/src/credentials/views/SetupIosDist.ts
  packages/expo-cli/src/credentials/views/SetupIosProvisioningProfile.ts
  packages/expo-cli/src/credentials/views/SetupIosPush.ts
  packages/expo-cli/src/credentials/views/__tests__/AndroidKeystore-Remove-test.ts
  packages/expo-cli/src/credentials/views/__tests__/IosDistCert-test.ts
  packages/expo-cli/src/credentials/views/__tests__/IosProvisioningProfile-test.ts
  packages/expo-cli/src/credentials/views/__tests__/IosPushCredentials-test.ts
  packages/expo-cli/src/credentials/views/__tests__/SetupIosDist-test.ts
  packages/expo-cli/src/credentials/views/__tests__/SetupIosPush-test.ts
  packages/expo-cli/src/credentials/views/__tests__/SetupProvisioningProfile-test.ts
Labels: 🔐 Credentials

#2444 [webpack-config] Add default support for use-expo namespace
  packages/webpack-config/src/loaders/createBabelLoader.ts
Labels: Platform: web

#2464 [cli][eject] Support projects with dynamic or missing configs
  packages/expo-cli/src/commands/eject/ConfigValidation.ts
  packages/expo-cli/src/commands/eject/Eject.ts
Labels: enhancement, expo eject

#2462 [config] allow scheme arrays
  packages/config/src/Config.types.ts
  packages/config/src/android/Scheme.ts
  packages/config/src/android/__tests__/Scheme-test.js
  packages/config/src/ios/Scheme.ts
  packages/config/src/ios/__tests__/Scheme-test.ts
  packages/dev-server/src/MetroDevServer.ts
  packages/xdl/src/UrlUtils.ts
  packages/xdl/src/detach/AndroidShellApp.js
  packages/xdl/src/detach/Detach.js
  packages/xdl/src/detach/IosNSBundle.ts
Labels: Expo config

#2475 [webpack-config] Disable offline support
  packages/webpack-config/README.md
  packages/webpack-config/e2e/__tests__/basic-test.js
  packages/webpack-config/e2e/basic/App.js
  packages/webpack-config/e2e/basic/app.config.js
  packages/webpack-config/src/__tests__/__snapshots__/webpack.config-test.js.snap
  packages/webpack-config/src/__tests__/webpack.config-test.js
  packages/webpack-config/src/index.ts
  packages/webpack-config/src/types.ts
  packages/webpack-config/src/webpack.config.ts
  packages/xdl/src/Webpack.ts
Labels: Platform: web

#2497 [apply] Fix iOS name changing
  packages/expo-cli/src/commands/apply/configureIOSProjectAsync.ts
Labels: bug

#2495 Generate iOS icons on eject and apply
  packages/config/package.json
  packages/config/src/ios/Icons.ts
  packages/config/src/ios/__tests__/Icons-test.ts
  packages/config/src/ios/__tests__/__snapshots__/Icons-test.ts.snap
  packages/config/src/ios/__tests__/fixtures/icons/icon.png
  packages/config/src/ios/utils/Xcodeproj.ts
  packages/expo-cli/src/commands/__tests__/publish-info-test.ts
  packages/expo-cli/src/commands/__tests__/publish-modify-test.ts
  packages/expo-cli/src/commands/build/__tests__/build-ios-test.ts
  packages/expo-cli/src/commands/eas-build/build/__tests__/build-test.ts
  packages/expo-cli/src/commands/eas-build/build/builders/__tests__/iOSBuilder-test.ts
  packages/expo-cli/src/commands/upload/submission-service/android/__tests__/AndroidSubmitCommand-test.ts
  packages/expo-cli/src/commands/utils/__tests__/ProjectUtils-test.ts
  packages/image-utils/src/Image.ts
  packages/image-utils/src/Image.types.ts
Labels: enhancement, expo eject

#2498 Prompt for bundle ID and package name in expo apply
  packages/expo-cli/src/commands/apply.ts
  packages/expo-cli/src/commands/apply/configureAndroidProjectAsync.ts
  packages/expo-cli/src/commands/apply/configureIOSProjectAsync.ts
  packages/expo-cli/src/commands/eject/ConfigValidation.ts
Labels: enhancement

#2505 [eject] Added support for device families
  packages/config/src/ios/DeviceFamily.ts
  packages/config/src/ios/__tests__/DeviceFamily-test.ts
Labels: enhancement

#2506 [eject] Added support for allowBackup
  packages/config/src/android/AllowBackup.ts
  packages/config/src/android/__tests__/AllowBackup-test.ts
  packages/config/src/android/__tests__/__snapshots__/Permissions-test.js.snap
  packages/config/src/android/__tests__/fixtures/react-native-AndroidManifest.xml
  packages/config/src/android/index.ts
  packages/expo-cli/src/commands/apply/configureAndroidProjectAsync.ts
Labels: enhancement

#2423 [webpack-config] fix: handle empty favicons
  packages/pwa/src/Manifest.ts
Labels: Platform: web

#2514 [webpack-config] Allow empty string to skip favicon generation - added tests
  packages/pwa/src/Manifest.ts
  packages/pwa/src/__tests__/Manifest-test.ts
Labels: Platform: web

#2515 [cli] Added no-install option to expo init
  packages/expo-cli/src/commands/init.ts
Labels: enhancement

#1440 fix(webpack-config): add compatibility for node-pushnotifications in service worker
  packages/webpack-config/web-default/expo-service-worker.js
Labels: Platform: web, enhancement

#2508 [Proposal] Implemented keychain storage for Apple ID
  packages/expo-cli/package.json
  packages/expo-cli/src/appleApi/authenticate.ts
  packages/expo-cli/src/appleApi/keychain.ts
  packages/expo-cli/src/commands/upload/IOSUploader.ts
  packages/xdl/src/UserSettings.ts
  yarn.lock
Labels: enhancement

#2516 [cli] Clean up upload results logs
  packages/expo-cli/package.json
  packages/expo-cli/src/commands/publish.ts
  yarn.lock
Labels: enhancement

#2527 [publish] Log bundles after building
  packages/xdl/package.json
  packages/xdl/src/Project.ts
  packages/xdl/src/logs/TableText.ts
  yarn.lock
Labels: enhancement

#2531 [cli] Remove web push commands
  CHANGELOG.md
  packages/expo-cli/src/commands/push-creds-web.ts
  packages/expo-cli/src/commands/push-creds.ts
Labels: Platform: web, 🧹 chore

#2538 [cli] Redesign help prompt
  CHANGELOG.md
  packages/dev-tools/server/dev-server.ts
  packages/expo-cli/e2e/__tests__/init-test.ts
  packages/expo-cli/package.json
  packages/expo-cli/src/commands/apply.ts
  packages/expo-cli/src/commands/build/index.ts
  packages/expo-cli/src/commands/bundle-assets.ts
  packages/expo-cli/src/commands/client/index.ts
  packages/expo-cli/src/commands/credentials.ts
  packages/expo-cli/src/commands/customize.ts
  packages/expo-cli/src/commands/diagnostics.ts
  packages/expo-cli/src/commands/doctor.ts
  packages/expo-cli/src/commands/eas-build/index.ts
  packages/expo-cli/src/commands/eject.ts
  packages/expo-cli/src/commands/export.ts
  packages/expo-cli/src/commands/fetch/index.ts
  packages/expo-cli/src/commands/generate-module.ts
  packages/expo-cli/src/commands/init.ts
  packages/expo-cli/src/commands/install.ts
  packages/expo-cli/src/commands/login.ts
  packages/expo-cli/src/commands/logout.ts
  packages/expo-cli/src/commands/prepare-detached-build.ts
  packages/expo-cli/src/commands/publish-info.ts
  packages/expo-cli/src/commands/publish-modify.ts
  packages/expo-cli/src/commands/publish.ts
  packages/expo-cli/src/commands/push-creds-web.ts
  packages/expo-cli/src/commands/push-creds.ts
  packages/expo-cli/src/commands/register.ts
  packages/expo-cli/src/commands/send.ts
  packages/expo-cli/src/commands/start.ts
  packages/expo-cli/src/commands/upgrade.ts
  packages/expo-cli/src/commands/upload.ts
  packages/expo-cli/src/commands/url.ts
  packages/expo-cli/src/commands/webhooks.ts
  packages/expo-cli/src/commands/whoami.ts
  packages/expo-cli/src/exp.ts
Labels: enhancement, 🧹 chore
