Repository expo/expo-cli, pull requests merged in 2020-11, with the labels that each got.

#2814 [config] Updated android branch support
  packages/config/src/android/Branch.ts
  packages/config/src/android/Manifest.ts
  packages/config/src/android/__tests__/Branch-test.js
  packages/config/src/android/__tests__/Branch-test.ts
Labels: enhancement

#2848 [config] Updated Android Facebook module to better accommodate plugins
  packages/config/src/Errors.ts
  packages/config/src/android/Facebook.ts
  packages/config/src/android/Manifest.ts
  packages/config/src/android/__tests__/Facebook-test.js
Labels: 🧹 chore

#2852 [config] iOS fix types
  packages/config/src/ios/Branch.ts
  packages/config/src/ios/CustomInfoPlistEntries.ts
  packages/config/src/ios/DeviceFamily.ts
  packages/config/src/ios/Facebook.ts
  packages/config/src/ios/Google.ts
  packages/config/src/ios/Icons.ts
  packages/config/src/ios/IosConfig.types.ts
  packages/config/src/ios/Locales.ts
  packages/config/src/ios/Name.ts
  packages/config/src/ios/Orientation.ts
  packages/config/src/ios/RequiresFullScreen.ts
  packages/config/src/ios/Scheme.ts
  packages/config/src/ios/SplashScreen.ts
  packages/config/src/ios/Updates.ts
  packages/config/src/ios/UserInterfaceStyle.ts
  packages/config/src/ios/UsesNonExemptEncryption.ts
  packages/config/src/ios/Version.ts
  packages/config/src/ios/__tests__/DeviceFamily-test.ts
  packages/config/src/ios/__tests__/Icons-test.ts
  packages/config/src/ios/__tests__/Locales-test.ts
  packages/config/src/ios/__tests__/Name-test.ts
  packages/config/src/ios/__tests__/Paths-test.ts
  packages/config/src/ios/__tests__/ProvisioningProfile-test.ts
  packages/config/src/ios/__tests__/Scheme-test.ts
  packages/config/src/ios/__tests__/Updates-test.ts
  packages/config/src/ios/__tests__/UserInterfaceStyle-test.ts
  packages/config/src/plugins/__tests__/core-plugins-test.ts
  packages/config/src/plugins/compiler-plugins.ts
Labels: 🧹 chore

#2851 [config] android fixes
  packages/config/src/android/AllowBackup.ts
  packages/config/src/android/Branch.ts
  packages/config/src/android/Colors.ts
  packages/config/src/android/EasBuild.ts
  packages/config/src/android/Facebook.ts
  packages/config/src/android/GoogleMapsApiKey.ts
  packages/config/src/android/GoogleMobileAds.ts
  packages/config/src/android/GoogleServices.ts
  packages/config/src/android/Icon.ts
  packages/config/src/android/IntentFilters.ts
  packages/config/src/android/Manifest.ts
  packages/config/src/android/Name.ts
  packages/config/src/android/NavigationBar.ts
  packages/config/src/android/Orientation.ts
  packages/config/src/android/Package.ts
  packages/config/src/android/Permissions.ts
  packages/config/src/android/PrimaryColor.ts
  packages/config/src/android/RootViewBackgroundColor.ts
  packages/config/src/android/Scheme.ts
  packages/config/src/android/StatusBar.ts
  packages/config/src/android/Strings.ts
  packages/config/src/android/Styles.ts
  packages/config/src/android/Updates.ts
  packages/config/src/android/UserInterfaceStyle.ts
  packages/config/src/android/Version.ts
  packages/config/src/android/__tests__/Facebook-test.ts
  packages/config/src/android/__tests__/GoogleMapsApiKey-test.js
  packages/config/src/android/__tests__/GoogleMapsApiKey-test.ts
  packages/config/src/android/__tests__/GoogleMobileAds-test.ts
  packages/config/src/android/__tests__/GoogleServices-test.ts
  packages/config/src/android/__tests__/IntentFilters-test.ts
  packages/config/src/android/__tests__/Manifest-test.ts
  packages/config/src/android/__tests__/Name-test.ts
  packages/config/src/android/__tests__/NavigationBar-test.ts
  packages/config/src/android/__tests__/Orientation-test.ts
  packages/config/src/android/__tests__/Package-test.ts
  packages/config/src/android/__tests__/Permissions-test.ts
  packages/config/src/android/__tests__/PrimaryColor-test.ts
  packages/config/src/android/__tests__/RootViewBackgroundColor-test.ts
  packages/config/src/android/__tests__/Scheme-test.ts
  packages/config/src/android/__tests__/StatusBar-test.ts
  packages/config/src/android/__tests__/Strings-test.ts
  packages/config/src/android/__tests__/Updates-test.ts
  packages/config/src/android/__tests__/UserInterfaceStyle-test.ts
  packages/config/src/android/__tests__/Version-test.ts
  packages/expo-cli/src/commands/apply/configureAndroidProjectAsync.ts
  packages/uri-scheme/src/Android.ts
Labels: 🧹 chore

#2860 Added support for a custom scheme property
  packages/expo-cli/src/urlOpts.ts
  packages/xdl/src/ProjectSettings.ts
  packages/xdl/src/UrlUtils.ts
Labels: enhancement

#2849 [config] android plugins
  packages/config/src/Plugin.types.ts
  packages/config/src/android/AllowBackup.ts
  packages/config/src/android/Branch.ts
  packages/config/src/android/Facebook.ts
  packages/config/src/android/GoogleMapsApiKey.ts
  packages/config/src/android/GoogleMobileAds.ts
  packages/config/src/android/GoogleServices.ts
  packages/config/src/android/Icon.ts
  packages/config/src/android/IntentFilters.ts
  packages/config/src/android/Manifest.ts
  packages/config/src/android/Name.ts
  packages/config/src/android/NavigationBar.ts
  packages/config/src/android/Orientation.ts
  packages/config/src/android/Package.ts
  packages/config/src/android/Paths.ts
  packages/config/src/android/Permissions.ts
  packages/config/src/android/PrimaryColor.ts
  packages/config/src/android/RootViewBackgroundColor.ts
  packages/config/src/android/Scheme.ts
  packages/config/src/android/SplashScreen.ts
  packages/config/src/android/StatusBar.ts
  packages/config/src/android/Updates.ts
  packages/config/src/android/UserInterfaceStyle.ts
  packages/config/src/android/Version.ts
  packages/config/src/android/__tests__/Paths-test.ts
  packages/config/src/android/__tests__/renamePackageOnDisk-test.ts
  packages/config/src/ios/Updates.ts
  packages/config/src/plugins/README.md
  packages/config/src/plugins/__tests__/__snapshots__/expo-plugins-test.ts.snap
  packages/config/src/plugins/__tests__/core-plugins-test.ts
  packages/config/src/plugins/__tests__/expo-plugins-test.ts
  packages/config/src/plugins/__tests__/fixtures/react-native-project.ts
  packages/config/src/plugins/android-plugins.ts
  packages/config/src/plugins/compiler-plugins.ts
  packages/config/src/plugins/core-plugins.ts
  packages/config/src/plugins/expo-plugins.ts
  packages/expo-cli/src/commands/apply/configureAndroidProjectAsync.ts
Labels: Expo config

#2869 [config] use void instead of any
  packages/config/src/Plugin.types.ts
  packages/config/src/android/GoogleServices.ts
  packages/config/src/android/Icon.ts
  packages/config/src/android/NavigationBar.ts
  packages/config/src/android/Package.ts
  packages/config/src/android/PrimaryColor.ts
  packages/config/src/android/RootViewBackgroundColor.ts
  packages/config/src/android/SplashScreen.ts
  packages/config/src/android/StatusBar.ts
  packages/config/src/android/UserInterfaceStyle.ts
  packages/config/src/android/Version.ts
  packages/config/src/ios/DeviceFamily.ts
  packages/config/src/ios/Google.ts
  packages/config/src/ios/Icons.ts
  packages/config/src/ios/Locales.ts
  packages/config/src/ios/SplashScreen.ts
  packages/config/src/plugins/__tests__/core-plugins-test.ts
  packages/config/src/plugins/android-plugins.ts
  packages/config/src/plugins/compiler-plugins.ts
  packages/config/src/plugins/ios-plugins.ts
Labels: 🧹 chore

#2867 [config] use config option instead of custom config method
  packages/config/src/Config.ts
  packages/config/src/Config.types.ts
  packages/expo-cli/src/commands/apply/configureAndroidProjectAsync.ts
  packages/expo-cli/src/commands/apply/configureIOSProjectAsync.ts
Labels: 🧹 chore

#2866 [config] clean up testing
  packages/config/__mocks__/@expo/image-utils.ts
  packages/config/__mocks__/fs.ts
  packages/config/__mocks__/resolve-from.ts
  packages/config/src/Config.ts
  packages/config/src/__tests__/Config-test.ts
  packages/config/src/__tests__/ConfigParsing-test.ts
  packages/config/src/__tests__/Modules-test.ts
  packages/config/src/__tests__/Serialize-test.ts
  packages/config/src/__tests__/Web-test.ts
  packages/config/src/__tests__/__snapshots__/Serialize-test.ts.snap
  packages/config/src/__tests__/fixtures/behavior/custom-location-json/app.json
  packages/config/src/__tests__/fixtures/behavior/custom-location-json/package.json
  packages/config/src/__tests__/fixtures/behavior/custom-location-json/src/app.staging.json
  packages/config/src/__tests__/fixtures/behavior/dynamic-and-static/app.config.js
  packages/config/src/__tests__/fixtures/behavior/dynamic-and-static/app.config.json
  packages/config/src/__tests__/fixtures/behavior/dynamic-and-static/package.json
  packages/config/src/__tests__/fixtures/behavior/dynamic-export-types/exports-function.app.config.js
  packages/config/src/__tests__/fixtures/behavior/dynamic-export-types/exports-object.app.config.js
  packages/config/src/__tests__/fixtures/behavior/no-config/package.json
  packages/config/src/__tests__/fixtures/behavior/static-override/app.config.json
  packages/config/src/__tests__/fixtures/behavior/static-override/app.json
  packages/config/src/__tests__/fixtures/behavior/static-override/package.json
  packages/config/src/__tests__/fixtures/behavior/syntax-error/app.config.js
  packages/config/src/__tests__/fixtures/behavior/syntax-error/app.config.ts
  packages/config/src/__tests__/fixtures/dynamic-cwd/app.config.ts
  packages/config/src/__tests__/fixtures/language-support/js/app.config.js
  packages/config/src/__tests__/fixtures/language-support/js/app.json
  packages/config/src/__tests__/fixtures/language-support/js/with-default_app.config.js
  packages/config/src/__tests__/fixtures/language-support/toml/app.config.toml
  packages/config/src/__tests__/fixtures/language-support/toml/app.toml
  packages/config/src/__tests__/fixtures/language-support/toml/package.json
  packages/config/src/__tests__/fixtures/language-support/ts/package.json
  packages/config/src/__tests__/fixtures/language-support/ts/tsconfig.json
  packages/config/src/__tests__/fixtures/language-support/yaml/app.config.yaml
  packages/config/src/__tests__/fixtures/language-support/yaml/app.yaml
  packages/config/src/__tests__/fixtures/language-support/yaml/package.json
  packages/config/src/__tests__/fixtures/require-file/export-json_app.config.js
  packages/config/src/__tests__/fixtures/require-file/package.json
  packages/config/src/__tests__/fixtures/require-file/with-import_app.config.js
  packages/config/src/__tests__/fixtures/ts/app.config.ts
  packages/config/src/__tests__/getConfig-e2e-test.ts
  packages/config/src/__tests__/getConfig-test.js
  packages/config/src/__tests__/getConfig-test.ts
  packages/config/src/android/__tests__/Icon-test.ts
  packages/config/src/android/__tests__/NavigationBar-test.ts
  packages/config/src/android/__tests__/fixtures/adaptiveIconBackground.png
  packages/config/src/android/__tests__/fixtures/adaptiveIconForeground.png
  packages/config/src/android/__tests__/fixtures/icon.png
  packages/config/src/ios/__tests__/DeviceFamily-test.ts
  packages/config/src/ios/__tests__/Entitlements-test.ts
  packages/config/src/ios/__tests__/Google-test.ts
  packages/config/src/ios/__tests__/Icons-test.ts
  packages/config/src/ios/__tests__/Locales-test.ts
  packages/config/src/ios/__tests__/Paths-test.ts
  packages/config/src/paths/__tests__/__snapshots__/extensions-test.ts.snap
  packages/config/src/paths/__tests__/extensions-test.ts
  packages/config/src/paths/__tests__/paths-test.ts
  packages/config/src/paths/paths.ts
  packages/config/src/plugins/__tests__/expo-plugins-test.ts
  packages/webpack-config/src/env/paths.ts
Labels: Expo config, 🧹 chore

#2872 [actions] Upgrade cache to v2
  .github/workflows/test.yml
Labels: 🧹 chore

#2887 [xdl] Record simctl error
  packages/xdl/src/SimControl.ts
Labels: 🧹 chore

#2886 [expo cli] delete legacy upload:android code
  packages/expo-cli/src/commands/upload.ts
  packages/expo-cli/src/commands/upload/submission-service/android/AndroidSubmitCommand.ts
  packages/expo-cli/src/commands/upload/submission-service/android/AndroidSubmitter.ts
  packages/expo-cli/src/commands/upload/submission-service/android/__tests__/AndroidSubmitCommand-test.ts
  packages/expo-cli/src/commands/upload/submission-service/archive-source/ArchiveFileSource.ts
  packages/expo-cli/src/commands/upload/submission-service/archive-source/index.ts
  packages/expo-cli/src/commands/upload/submission-service/types.ts
Labels: 🧹 chore

#2893 unify clear logs
  packages/expo-cli/src/commands/start/TerminalUI.ts
  packages/expo-cli/src/log.ts
  packages/xdl/src/webpack-utils/createWebpackCompiler.ts
Labels: 🧹 chore

#2891 [xdl] Replace inquirer with prompts
  packages/xdl/package.json
  packages/xdl/src/detach/Detach.js
Labels: 🧹 chore

#2892 [expo cli] mostly remove inquirer
  packages/expo-cli/src/accounts.ts
  packages/expo-cli/src/appleApi/authenticate.ts
  packages/expo-cli/src/askUser.ts
  packages/expo-cli/src/commands/client/index.ts
  packages/expo-cli/src/commands/eject/ConfigValidation.ts
  packages/expo-cli/src/commands/upload/IOSUploader.ts
  packages/expo-cli/src/commands/upload/submission-service/android/AndroidPackageSource.ts
  packages/expo-cli/src/commands/upload/submission-service/android/ServiceAccountSource.ts
  packages/expo-cli/src/commands/upload/submission-service/android/__tests__/ServiceAccountSource-test.ts
  packages/expo-cli/src/commands/upload/submission-service/archive-source/ArchiveFileSource.ts
  packages/expo-cli/src/commands/upload/submission-service/archive-source/ArchiveTypeSource.ts
  packages/expo-cli/src/commands/utils/ClientUpgradeUtils.ts
  packages/expo-cli/src/credentials/views/AndroidCredentials.ts
  packages/expo-cli/src/credentials/views/AndroidPushCredentials.ts
  packages/expo-cli/src/credentials/views/IosDistCert.ts
  packages/expo-cli/src/credentials/views/IosProvisioningProfile.ts
  packages/expo-cli/src/credentials/views/IosPushCredentials.ts
  packages/expo-cli/src/credentials/views/Select.ts
  packages/expo-cli/src/prompts.ts
Labels: 🧹 chore

#2889 promote web warning to late beta
  packages/xdl/src/Webpack.ts
  packages/xdl/src/webpack-utils/createWebpackCompiler.ts
Labels: Platform: web, 🧹 chore

#2890 [xdl] Update web terminal UI
  packages/expo-cli/src/commands/start/TerminalUI.ts
  packages/xdl/src/Webpack.ts
  packages/xdl/src/project/ProjectUtils.ts
  packages/xdl/src/webpack-utils/createWebpackCompiler.ts
Labels: enhancement

#2888 [cli][upgrade] support projects without a config
  packages/expo-cli/src/commands/upgrade.ts
Labels: enhancement

#2900 Refactor ConfigUtils imports
  packages/expo-cli/src/commands/customize.ts
  packages/expo-cli/src/commands/eject/LegacyEject.ts
  packages/expo-cli/src/commands/install.ts
  packages/expo-cli/src/commands/upgrade.ts
  packages/expo-cli/src/commands/utils/ClientUpgradeUtils.ts
  packages/expo-cli/src/exp.ts
  packages/xdl/src/Webpack.ts
Labels: 🧹 chore

#2898 [cli] remove unused process.exit() in doctor
  packages/expo-cli/src/commands/doctor.ts
Labels: 🧹 chore

#2907 Improve PWA warning
  packages/xdl/src/Webpack.ts
Labels: Platform: web

#2899 [cli] Delete apply command in favor of eject
  packages/expo-cli/src/commands/apply.ts
  packages/expo-cli/src/commands/index.ts
Labels: 🧹 chore

#2902 Remove es6-error in favor of Error
  packages/expo-cli/package.json
  packages/expo-cli/src/CommandError.ts
  packages/expo-cli/src/commands/build/BuildError.ts
  packages/schemer/package.json
  packages/schemer/src/Error.ts
  packages/xdl/package.json
  packages/xdl/src/Api.ts
  packages/xdl/src/ApiV2.ts
  packages/xdl/src/TurtleApi.ts
  packages/xdl/src/XDLError.ts
  yarn.lock
Labels: 🧹 chore

#2904 Remove inquirer from LegacyEject
  packages/expo-cli/src/commands/eject/LegacyEject.ts
Labels: 🧹 chore

#2903 [cli] delete generate-module
  CHANGELOG.md
  packages/expo-cli/package.json
  packages/expo-cli/src/commands/generate-module.ts
  packages/expo-cli/src/commands/generate-module/ModuleConfiguration.ts
  packages/expo-cli/src/commands/generate-module/configureModule.ts
  packages/expo-cli/src/commands/generate-module/fetchTemplate.ts
  packages/expo-cli/src/commands/generate-module/generateModuleAsync.ts
  packages/expo-cli/src/commands/generate-module/promptQuestionsAsync.ts
  packages/expo-cli/src/commands/index.ts
Labels: 🧹 chore

#2913 resolve empty hermes package
  package.json
  yarn.lock
Labels: 🧹 chore

#2897 Remove submission-service flag warning
  packages/expo-cli/src/commands/upload.ts
Labels: 🧹 chore

#2871 [config] permissions plugins
  packages/config/src/android/Permissions.ts
  packages/config/src/ios/Permissions.ts
  packages/config/src/ios/__tests__/Permissions-test.ts
  packages/config/src/ios/index.ts
Labels: enhancement

#2919 remove clipboardy
  packages/expo-cli/package.json
  yarn.lock
Labels: 🧹 chore

#2905 [cli] Replace inquirer with prompts in init
  packages/expo-cli/package.json
  packages/expo-cli/src/__mocks__/prompt.ts
  packages/expo-cli/src/commands/init.ts
  packages/expo-cli/src/prompt.ts
  packages/expo-cli/src/prompts.ts
  yarn.lock
Labels: 🧹 chore

#2921 [xdl] Switch to in-process Metro JS bundling starting from SDK 40
  CHANGELOG.md
  packages/xdl/src/Project.ts
Labels: enhancement, 🧹 chore

#2901 Replace process.exits with errors
  packages/config/src/Errors.ts
  packages/expo-cli/e2e/__tests__/eject-test.ts
  packages/expo-cli/src/CommandError.ts
  packages/expo-cli/src/commands/build/index.ts
  packages/expo-cli/src/commands/bundle-assets.ts
  packages/expo-cli/src/commands/eject.ts
  packages/expo-cli/src/commands/eject/ConfigValidation.ts
  packages/expo-cli/src/commands/eject/Eject.ts
  packages/expo-cli/src/commands/export.ts
  packages/expo-cli/src/commands/init.ts
  packages/expo-cli/src/commands/install.ts
  packages/expo-cli/src/commands/publish.ts
  packages/expo-cli/src/commands/push-creds.ts
  packages/expo-cli/src/exp.ts
Labels: 🧹 chore

#2923 wrap links correctly in the help prompt
  packages/expo-cli/package.json
  packages/expo-cli/src/exp.ts
  yarn.lock
Labels: enhancement

#2925 use command error for logout
  packages/expo-cli/src/commands/logout.ts
Labels: error message improvement needed, 🧹 chore

#2924 added types for envinfo
  packages/expo-cli/src/commands/diagnostics.ts
  ts-declarations/envinfo/index.d.ts
Labels: 🧹 chore

#2922 split up ngrok code
  packages/xdl/src/Project.ts
  packages/xdl/src/project/errors.ts
  packages/xdl/src/project/ngrok.ts
Labels: 🧹 chore

#2929 clean up fetch commands
  packages/expo-cli/src/commands/fetch/android.ts
  packages/expo-cli/src/commands/fetch/index.ts
  packages/expo-cli/src/commands/fetch/ios.ts
Labels: 🧹 chore

#2926 clean up send command
  packages/expo-cli/src/askUser.ts
  packages/expo-cli/src/commands/client/index.ts
  packages/expo-cli/src/commands/publish.ts
  packages/expo-cli/src/commands/send.ts
  packages/expo-cli/src/commands/start.ts
  packages/expo-cli/src/prompts.ts
  packages/expo-cli/src/sendTo.ts
Labels: 🧹 chore

#2931 Support grouping and hiding in the introspect script
  packages/expo-cli/scripts/introspect.ts
  packages/expo-cli/src/exp.ts
Labels: enhancement

#2906 upgrade react-dev-utils to 11.0.1
  packages/expo-cli/package.json
  packages/json-file/package.json
  packages/webpack-config/package.json
  packages/xdl/package.json
  yarn.lock
Labels: 🧹 chore

#2937 Prevent passing a plugin that requires props without props
  packages/config/src/plugins/core-plugins.ts
Labels: 🧹 chore

#2941 Delete empty BuildCredentials.ts
  packages/config/src/ios/BuildCredentials.ts
Labels: 🧹 chore

#2946 [cli] debug logging
  packages/expo-cli/src/commands/apply/configureAndroidProjectAsync.ts
  packages/expo-cli/src/commands/apply/configureIOSProjectAsync.ts
  packages/expo-cli/src/commands/eject.ts
  packages/expo-cli/src/commands/eject/Eject.ts
  packages/expo-cli/src/log.ts
Labels: enhancement

#2949 name all config plugins
  packages/config/src/android/AllowBackup.ts
  packages/config/src/android/Branch.ts
  packages/config/src/android/Facebook.ts
  packages/config/src/android/GoogleMapsApiKey.ts
  packages/config/src/android/GoogleMobileAds.ts
  packages/config/src/android/IntentFilters.ts
  packages/config/src/android/Name.ts
  packages/config/src/android/Orientation.ts
  packages/config/src/android/Package.ts
  packages/config/src/android/Scheme.ts
  packages/config/src/android/UserInterfaceStyle.ts
  packages/config/src/ios/Branch.ts
  packages/config/src/ios/Entitlements.ts
  packages/config/src/ios/Facebook.ts
  packages/config/src/ios/Google.ts
  packages/config/src/ios/Name.ts
  packages/config/src/ios/Orientation.ts
  packages/config/src/ios/RequiresFullScreen.ts
  packages/config/src/ios/Scheme.ts
  packages/config/src/ios/UserInterfaceStyle.ts
  packages/config/src/ios/UsesNonExemptEncryption.ts
  packages/config/src/ios/Version.ts
  packages/config/src/plugins/android-plugins.ts
  packages/config/src/plugins/core-plugins.ts
  packages/config/src/plugins/ios-plugins.ts
Labels: enhancement

#2948 [config plugins] base mod improvements
  packages/config/src/Plugin.types.ts
  packages/config/src/ios/utils/Xcodeproj.ts
  packages/config/src/plugins/README.md
  packages/config/src/plugins/__tests__/expo-plugins-test.ts
  packages/config/src/plugins/__tests__/plugin-compiler-test.ts
  packages/config/src/plugins/compiler-plugins.ts
  packages/config/src/plugins/core-plugins.ts
  packages/config/src/plugins/mod-compiler.ts
Labels: 🧹 chore

#2955 Support updating the project settings.gradle name on sync
  packages/config/src/Plugin.types.ts
  packages/config/src/android/Name.ts
  packages/config/src/android/Paths.ts
  packages/config/src/android/__tests__/Name-test.ts
  packages/config/src/plugins/android-plugins.ts
  packages/config/src/plugins/compiler-plugins.ts
  packages/config/src/plugins/expo-plugins.ts
Labels: Expo config, android, expo eject

#2958 Enable notifications by default
  packages/config/src/ios/Entitlements.ts
  packages/config/src/ios/__tests__/Entitlements-test.ts
  packages/config/src/plugins/__tests__/__snapshots__/expo-plugins-test.ts.snap
Labels: enhancement

#2920 upgrade to expo/bunyan@4.0.0
  packages/dev-server/package.json
  packages/expo-cli/package.json
  packages/xdl/package.json
  yarn.lock
Labels: 🧹 chore

#2963 Upgraded jimp to the smaller version
  packages/image-utils/package.json
  packages/image-utils/src/Download.ts
  packages/image-utils/src/jimp.ts
  yarn.lock
Labels: 🧹 chore

#2968 [config] fill _internal object
  packages/config-plugins/src/Plugin.types.ts
  packages/config-plugins/src/plugins/core-plugins.ts
  packages/config-plugins/src/plugins/mod-compiler.ts
  packages/config/package.json
  packages/config/src/Config.ts
  packages/config/src/__tests__/Config-test.ts
  packages/config/src/__tests__/ConfigParsing-test.ts
Labels: Expo config

#2965 Created withRunOnce
  packages/config-plugins/src/index.ts
  packages/config-plugins/src/ios/Facebook.ts
  packages/config-plugins/src/plugins/__tests__/core-plugins-test.ts
  packages/config-plugins/src/plugins/core-plugins.ts
  packages/config-plugins/src/utils/deprecation.ts
  packages/config-plugins/src/utils/history.ts
  packages/config-plugins/src/utils/warnings.ts
Labels: Expo config, enhancement

#2975 withInternal plugin
  packages/config/src/Config.ts
  packages/config/src/Config.types.ts
  packages/config/src/plugins/withInternal.ts
Labels: 🧹 chore
