Repository expo/expo-cli, pull requests merged in 2020-06, with the labels that each got.

#2217 [expo-cli] Updated syntax for send command
  packages/expo-cli/src/askUser.ts
  packages/expo-cli/src/commands/send.ts
Labels: 🧹 chore

#2251 Upgrade find-yarn-workspace-root
  packages/package-manager/package.json
  packages/webpack-config/package.json
  yarn.lock
Labels: 🧹 chore

#2218 refactor: unify glob usage
  packages/config/package.json
  packages/config/src/Config.ts
  packages/config/src/android/Package.ts
  packages/config/src/ios/BundleIdentifier.ts
  packages/config/src/ios/Entitlements.ts
  packages/config/src/ios/utils/Xcodeproj.ts
  packages/expo-optimize/src/assets.ts
  packages/metro-config/package.json
  packages/uri-scheme/src/Android.ts
  packages/uri-scheme/src/Ios.ts
  packages/xdl/package.json
  packages/xdl/src/Simulator.ts
  packages/xdl/src/detach/AndroidIcons.ts
  packages/xdl/src/detach/AndroidShellApp.js
  packages/xdl/src/detach/Detach.js
  packages/xdl/src/detach/IosCodeSigning.js
  packages/xdl/src/detach/IosPodsTools.js
  packages/xdl/src/detach/IosSetBundleIdentifier.ts
Labels: 🧹 chore

#2260 Adjust config types to take defaults in account
  packages/config/src/Config.ts
  packages/config/src/Config.types.ts
  packages/config/src/ios/Scheme.ts
  packages/expo-cli/src/commands/build/BaseBuilder.ts
  packages/expo-cli/src/commands/build/__tests__/build-ios-test.ts
  packages/expo-cli/src/commands/client/clientBuildApi.ts
  packages/expo-cli/src/commands/init.ts
  packages/pwa/src/Manifest.ts
  packages/pwa/src/Manifest.types.ts
  packages/pwa/src/index.ts
  packages/webpack-config/src/env/getConfig.ts
  packages/webpack-config/src/plugins/ExpoInterpolateHtmlPlugin.ts
  packages/webpack-config/src/types.ts
  packages/xdl/src/Exp.ts
  packages/xdl/src/Webpack.ts
Labels: 🧹 chore

#2269 [image-utils] add env variable to disable sharp resolution
  .github/workflows/test.yml
  packages/image-utils/README.md
  packages/image-utils/jest.config.js
  packages/image-utils/package.json
  packages/image-utils/src/__tests__/sharp-test.ts
  packages/image-utils/src/sharp.ts
Labels: enhancement

#2283 Mark functions as deprecated
  packages/expo-cli/src/prompt.ts
  packages/xdl/src/Api.ts
  packages/xdl/src/Exp.ts
  packages/xdl/src/credentials/Credentials.ts
  packages/xdl/src/tools/ModuleVersion.ts
Labels: 🧹 chore

#2303 [package manager] Prompt the user to use sudo to install CocoaPods
  packages/expo-cli/src/commands/eject/Eject.ts
  packages/expo-cli/src/commands/init.ts
  packages/package-manager/src/CocoaPodsPackageManager.ts
  packages/package-manager/src/PackageManager.ts
Labels: enhancement

#2306 [expo-cli][build:ios] Added prompt to supply bundle identifier
  packages/expo-cli/e2e/TestUtils.ts
  packages/expo-cli/src/commands/build/AndroidBuilder.ts
  packages/expo-cli/src/commands/build/BaseBuilder.ts
  packages/expo-cli/src/commands/build/__tests__/build-ios-test.ts
  packages/expo-cli/src/commands/build/index.ts
  packages/expo-cli/src/commands/build/ios/IOSBuilder.ts
Labels: enhancement, expo build
