Repository expo/expo-cli, pull requests merged in 2021-02, with the labels that each got.

#3141 Drop nodeModulesPath support
  packages/config-plugins/package.json
  packages/config-plugins/src/android/Updates.ts
  packages/config-plugins/src/android/__tests__/Updates-test.ts
  packages/config-plugins/src/ios/Updates.ts
  packages/config-plugins/src/ios/__tests__/Updates-test.ts
  packages/config-plugins/src/utils/modules.ts
  packages/config-types/src/ExpoConfig.ts
  packages/config/src/Config.ts
  packages/config/src/Modules.ts
  packages/config/src/Project.ts
  packages/config/src/__tests__/Modules-test.ts
  packages/config/src/index.ts
  packages/config/src/paths/paths.ts
  packages/config/src/resolvePackageJson.ts
  packages/electron-adapter/src/Config.ts
  packages/expo-cli/e2e/__tests__/install-test.ts
  packages/expo-cli/src/commands/install.ts
  packages/expo-cli/src/commands/start.ts
  packages/expo-cli/src/commands/upgrade.ts
  packages/expo-cli/src/commands/utils/typescript/resolveModules.ts
  packages/expo-optimize/src/assets.ts
  packages/metro-config/src/ExpoMetroConfig.ts
  packages/next-adapter/package.json
  packages/next-adapter/src/customize/manifest.ts
  packages/schemer/__tests__/files/schema.json
  packages/webpack-config/__mocks__/resolve-from.ts
  packages/webpack-config/jest/unit-test-config.js
  packages/webpack-config/src/__tests__/webpack.config-test.js
  packages/webpack-config/src/addons/__tests__/withEntry-test.js
  packages/webpack-config/src/addons/index.ts
  packages/webpack-config/src/addons/withEntry.ts
  packages/webpack-config/src/addons/withTypeScriptAsync.ts
  packages/webpack-config/src/env/__tests__/paths-test.js
  packages/webpack-config/src/env/alias.ts
  packages/webpack-config/src/loaders/createBabelLoader.ts
  packages/webpack-config/src/webpack.config.ts
  packages/xdl/src/Project.ts
  packages/xdl/src/UrlUtils.ts
  packages/xdl/src/__tests__/UrlUtils-test.ts
  packages/xdl/src/detach/Detach.js
  packages/xdl/src/project/Doctor.ts
Labels: 🧹 chore

#3175 Use devcert fork
  packages/package-manager/package.json
  packages/xdl/package.json
  packages/xdl/src/Webpack.ts
  yarn.lock
Labels: 🧹 chore

#3172 [expo-cli] npm ignore credentials fixtures properly
  packages/expo-cli/src/__tests__/accounts-test.ts
  packages/expo-cli/src/commands/__tests__/export-test.ts
  packages/expo-cli/src/commands/__tests__/publish-info-test.ts
  packages/expo-cli/src/commands/__tests__/publish-modify-test.ts
  packages/expo-cli/src/commands/build/__tests__/build-ios-test.ts
  packages/expo-cli/src/credentials/__tests__/api-android-basic-test.ts
  packages/expo-cli/src/credentials/__tests__/api-ios-basic-test.ts
  packages/expo-cli/src/credentials/__tests__/fixtures/mock-base64-data.ts
  packages/expo-cli/src/credentials/__tests__/fixtures/mocks-android.ts
  packages/expo-cli/src/credentials/__tests__/fixtures/mocks-constants.ts
  packages/expo-cli/src/credentials/__tests__/fixtures/mocks-context.ts
  packages/expo-cli/src/credentials/__tests__/fixtures/mocks-ios.ts
  packages/expo-cli/src/credentials/credentialsJson/__tests__/update-test.ts
  packages/expo-cli/src/credentials/utils/__tests__/provisioningProfile-test.ts
  packages/expo-cli/src/credentials/views/__tests__/AndroidKeystore-Remove-test.ts
  packages/expo-cli/src/credentials/views/__tests__/AndroidKeystore-Update-test.ts
  packages/expo-cli/src/credentials/views/__tests__/IosDistCert-test.ts
  packages/expo-cli/src/credentials/views/__tests__/IosProvisioningProfile-test.ts
  packages/expo-cli/src/credentials/views/__tests__/IosPushCredentials-test.ts
  packages/expo-cli/src/credentials/views/__tests__/SetupAndroidBuildCredentialsFromLocal-test.ts
  packages/expo-cli/src/credentials/views/__tests__/SetupAndroidKeystore-test.ts
  packages/expo-cli/src/credentials/views/__tests__/SetupIosBuildCredentialsFromLocal-test.ts
  packages/expo-cli/src/credentials/views/__tests__/SetupIosDist-test.ts
  packages/expo-cli/src/credentials/views/__tests__/SetupIosPush-test.ts
  packages/expo-cli/src/credentials/views/__tests__/SetupProvisioningProfile-test.ts
Labels: 🧹 chore

#3171 [expo-cli] remove unused slash package
  packages/expo-cli/package.json
  yarn.lock
Labels: 🧹 chore

#3167 Remove idx package
  packages/xdl/package.json
  packages/xdl/src/ApiV2.ts
  packages/xdl/src/TurtleApi.ts
  yarn.lock
Labels: 🧹 chore

#3179 [expo-pwa] Remove extra deps
  packages/pwa/package.json
  packages/pwa/src/cli.ts
Labels: 🧹 chore

#3174 Drop unused Doctor code
  packages/xdl/src/project/Doctor.ts
Labels: 🧹 chore

#3168 match the version of serialize-error used in dev-server
  packages/xdl/package.json
  yarn.lock
Labels: 🧹 chore

#3180 [expo-cli] strip unused git functions
  packages/expo-cli/src/__mocks__/git.ts
  packages/expo-cli/src/git.ts
Labels: 🧹 chore

#3178 [configure-splash-screen] Remove @react-native-community/cli-tools
  CHANGELOG.md
  unlinked-packages/configure-splash-screen/package.json
  unlinked-packages/configure-splash-screen/src/ios/Paths.ts
  unlinked-packages/configure-splash-screen/src/ios/pbxproj.ts
  unlinked-packages/configure-splash-screen/src/ts-declarations/@react-native-community/cli-platform-android.d.ts
  unlinked-packages/configure-splash-screen/src/ts-declarations/@react-native-community/cli-platform-ios.d.ts
  unlinked-packages/configure-splash-screen/yarn.lock
Labels: 🧹 chore

#3164 [xdl] split up Project module
  packages/dev-tools/__mocks__/@expo/xdl.js
  packages/dev-tools/server/graphql/GraphQLSchema.ts
  packages/expo-cli/src/commands/upgrade.ts
  packages/expo-cli/src/commands/url.ts
  packages/expo-cli/src/exp.ts
  packages/xdl/src/Project.ts
  packages/xdl/src/ProjectSettings.ts
  packages/xdl/src/project/exportAppAsync.ts
  packages/xdl/src/project/findReusableBuildAsync.ts
  packages/xdl/src/project/getBuildStatusAsync.ts
  packages/xdl/src/project/getFreePortAsync.ts
  packages/xdl/src/project/getLatestReleaseAsync.ts
  packages/xdl/src/project/getPublishExpConfigAsync.ts
  packages/xdl/src/project/mergeAppDistributions.ts
  packages/xdl/src/project/publishAsync.ts
  packages/xdl/src/project/runHook.ts
  packages/xdl/src/project/startBuildAsync.ts
  packages/xdl/src/project/startDevServerAsync.ts
  packages/xdl/src/project/startLegacyExpoServerAsync.ts
  packages/xdl/src/project/startLegacyReactNativeServerAsync.ts
Labels: 🧹 chore

#3190 [xdl] Improve keytool errors
  packages/xdl/src/credentials/AndroidCredentials.ts
Labels: enhancement, 🔐 Credentials

#3188 [expo-cli][upgrade] Cancel command on ctrl+c
  packages/expo-cli/src/commands/upgrade.ts
Labels: expo upgrade

#3187 Move legacy build methods to expo-cli
  CHANGELOG.md
  packages/expo-cli/src/commands/build/BaseBuilder.ts
  packages/expo-cli/src/commands/build/__tests__/build-ios-test.ts
  packages/expo-cli/src/commands/build/findReusableBuildAsync.ts
  packages/expo-cli/src/commands/build/getBuildStatusAsync.ts
  packages/expo-cli/src/commands/build/getLatestReleaseAsync.ts
  packages/expo-cli/src/commands/build/startBuildAsync.ts
  packages/expo-cli/src/commands/publish.ts
  packages/expo-cli/src/commands/url.ts
  packages/xdl/src/Project.ts
Labels: 🧹 chore

#3186 [xdl] refactor start command folder
  packages/xdl/src/Env.ts
  packages/xdl/src/Project.ts
  packages/xdl/src/project/exportAppAsync.ts
  packages/xdl/src/project/publishAsync.ts
  packages/xdl/src/start/ManifestHandler.ts
  packages/xdl/src/start/__tests__/ManifestHandler-test.ts
  packages/xdl/src/start/__tests__/__snapshots__/ManifestHandler-test.ts.snap
  packages/xdl/src/start/__tests__/fixtures/icon.png
  packages/xdl/src/start/getFreePortAsync.ts
  packages/xdl/src/start/ngrok.ts
  packages/xdl/src/start/resolveNgrok.ts
  packages/xdl/src/start/startAsync.ts
  packages/xdl/src/start/startDevServerAsync.ts
  packages/xdl/src/start/startLegacyExpoServerAsync.ts
  packages/xdl/src/start/startLegacyReactNativeServerAsync.ts
Labels: 🧹 chore

#3189 [webpack] Fixed support for disabling automatic manifest.json tag injection
  packages/webpack-config/src/plugins/PwaManifestWebpackPlugin.ts
  packages/webpack-config/src/webpack.config.ts
Labels: Platform: web

#3170 Unify node version
  package.json
  packages/expo-cli/src/commands/start/TerminalUI.ts
  packages/expo-optimize/package.json
  packages/pod-install/package.json
  packages/pwa/package.json
  packages/schemer/package.json
  packages/uri-scheme/package.json
  packages/webpack-config/package.json
  yarn.lock
Labels: 🧹 chore

#3201 [expo-cli][prebuild] Clean up debug error messages
  packages/config-plugins/src/plugins/static-plugins.ts
Labels: 🧹 chore

#3199 Update web index.html height style
  packages/webpack-config/web-default/index.html
Labels: Platform: web

#3200 [prebuild] refactor and test
  packages/expo-cli/src/commands/eject.ts
  packages/expo-cli/src/commands/eject/Eject.ts
  packages/expo-cli/src/commands/eject/__tests__/createNativeProjectsFromTemplateAsync-test.ts
  packages/expo-cli/src/commands/eject/__tests__/ensureConfigAsync-test.ts
  packages/expo-cli/src/commands/eject/__tests__/platformOptions-test.ts
  packages/expo-cli/src/commands/eject/__tests__/setupWarnings-test.ts
  packages/expo-cli/src/commands/eject/__tests__/updatePackageJson-test.ts
  packages/expo-cli/src/commands/eject/clearNativeFolder.ts
  packages/expo-cli/src/commands/eject/createNativeProjectsFromTemplateAsync.ts
  packages/expo-cli/src/commands/eject/ejectAsync.ts
  packages/expo-cli/src/commands/eject/ensureConfigAsync.ts
  packages/expo-cli/src/commands/eject/installNodeDependenciesAsync.ts
  packages/expo-cli/src/commands/eject/logNextSteps.ts
  packages/expo-cli/src/commands/eject/platformOptions.ts
  packages/expo-cli/src/commands/eject/prebuildAsync.ts
  packages/expo-cli/src/commands/eject/setupWarnings.ts
  packages/expo-cli/src/commands/eject/updatePackageJson.ts
  packages/expo-cli/src/commands/eject/writeMetroConfig.ts
  packages/expo-cli/src/commands/prebuild.ts
Labels: expo prebuild, 🧹 chore

#3205 Added clear flag to expo export
  packages/expo-cli/src/commands/export.ts
Labels: expo export

#3211 [expo-cli] refactor email prompt to use prompts
  packages/expo-cli/src/commands/start/TerminalUI.ts
Labels: 🧹 chore

#3210 [expo-cli] Improve server stopping
  packages/expo-cli/src/exit.ts
  packages/xdl/src/Webpack.ts
  packages/xdl/src/start/startAsync.ts
  packages/xdl/src/start/startDevServerAsync.ts
Labels: enhancement

#3234 remove vars from the repo
  packages/expo-cli/bin/expo.js
  packages/expo-cli/src/exp.ts
  packages/expo-cli/src/urlOpts.ts
  packages/expo-codemod/bin/expo-codemod.js
  packages/json-file/__tests__/JsonFile-test.ts
  packages/traveling-fastlane/publishing/linux/platform.js
  packages/xdl/src/Api.ts
  packages/xdl/src/Session.ts
  packages/xdl/src/UserSettings.ts
Labels: 🧹 chore

#3231 [expo cli] refactor url command
  packages/expo-cli/src/commands/url.ts
Labels: 🧹 chore

#3236 Remove default metro logger from default metro config
  packages/metro-config/src/ExpoMetroConfig.ts
Labels: enhancement

#3237 [expo-cli] Combine stop methods for web and native
  packages/expo-cli/src/commands/start.ts
  packages/expo-cli/src/commands/start/installExitHooks.ts
  packages/xdl/src/Project.ts
  packages/xdl/src/start/startAsync.ts
Labels: 🧹 chore

#3216 [expo-cli][start] deprecate .expo extension for start command
  packages/config/src/Config.ts
  packages/config/src/isLegacyImportsEnabled.ts
  packages/dev-server/src/MetroDevServer.ts
  packages/expo-cli/package.json
  packages/expo-cli/src/commands/export.ts
  packages/expo-cli/src/commands/start.ts
  packages/expo-cli/src/commands/upgrade.ts
  packages/expo-cli/src/commands/utils/deprecatedExtensionWarnings.ts
  packages/expo-cli/src/urlOpts.ts
  packages/metro-config/package.json
  packages/metro-config/src/ExpoMetroConfig.ts
  packages/metro-config/src/__tests__/ExpoMetroConfig-test.ts
  packages/metro-config/src/__tests__/__snapshots__/ExpoMetroConfig-test.ts.snap
  packages/xdl/src/Env.ts
  packages/xdl/src/project/exportAppAsync.ts
  packages/xdl/src/project/getPublishExpConfigAsync.ts
  packages/xdl/src/project/publishAsync.ts
  packages/xdl/src/start/startDevServerAsync.ts
Labels: enhancement

#3240 [expo-cli] refactor and test start command
  packages/expo-cli/src/commands/start.ts
  packages/expo-cli/src/commands/start/__tests__/parseStartOptions-test.ts
  packages/expo-cli/src/commands/start/openDevTools.ts
  packages/expo-cli/src/commands/start/parseStartOptions.ts
  packages/expo-cli/src/commands/start/validateDependenciesVersions.ts
Labels: 🧹 chore

#3241 remove expo extensions prompt in expo upgrade
  packages/expo-cli/src/commands/utils/deprecatedExtensionWarnings.ts
Labels: expo upgrade

#3245 [config-plugins] Pass updates props to plugin
  packages/config-plugins/src/plugins/unversioned/expo-updates.ts
Labels: enhancement

#3244 Added system for hiding legacy plugin errors
  packages/config-plugins/README.md
  packages/config-plugins/src/plugins/static-plugins.ts
  packages/config-plugins/src/plugins/unversioned/expo-ads-admob.ts
  packages/config-plugins/src/plugins/unversioned/expo-apple-authentication.ts
  packages/config-plugins/src/plugins/unversioned/expo-branch.ts
  packages/config-plugins/src/plugins/unversioned/expo-document-picker.ts
  packages/config-plugins/src/plugins/unversioned/expo-facebook.ts
  packages/config-plugins/src/plugins/unversioned/expo-notifications.ts
  packages/config-plugins/src/plugins/unversioned/expo-splash-screen.ts
  packages/config-plugins/src/plugins/unversioned/expo-updates.ts
  packages/expo-cli/src/commands/eject/configureProjectAsync.ts
Labels: enhancement

#3249 [publish] silence workflow warning in 41
  packages/expo-cli/src/commands/publish.ts
Labels: 🧹 chore

#3208 Use a more focused babel preset for app.config.js
  packages/config/package.json
  packages/config/src/__tests__/fixtures/ts/app.config.ts
  packages/config/src/evalConfig.ts
  packages/config/src/getBabelPreset.ts
  yarn.lock
Labels: 🧹 chore

#3257 [prebuild] Skip overwriting modules that are symlinked
  packages/expo-cli/package.json
  packages/expo-cli/src/commands/eject/updatePackageJson.ts
  packages/expo-cli/src/commands/utils/__tests__/isModuleSymlinked-test.ts
  packages/expo-cli/src/commands/utils/isModuleSymlinked.ts
  yarn.lock
Labels: expo prebuild
